### ISSUE TITLE
E_ERROR when upgrading from PHP 7 to PHP 8

### ISSUE THREAD

**Issue by idh-86** [NHSLeadership/nightingale-companion#45] opened 2022-07-25 11:38 UTC
WordPress gives me a critical error when I upgrade to PHP 8. The automated email points to the Nightingale Companion as the cause with the following error details (website name amended):

`An error of type E_ERROR was caused in line 282 of the file /home/u000/domains/website.co.uk/public_html/wp-content/plugins/nightingale-companion/RationalOptionPages.php. Error message: Uncaught Error: Unknown named parameter $checked in /home/u000/domains/website.co.uk/public_html/wp-content/plugins/nightingale-companion/RationalOptionPages.php:282
Stack trace:
#0 /home/u000/domains/website.co.uk/public_html/wp-includes/class-wp-hook.php(307): RationalOptionPages->admin_init()
#1 /home/u000/domains/website.co.uk/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /home/u000/domains/website.co.uk/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#3 /home/u000/domains/website.co.uk/public_html/wp-admin/admin.php(175): do_action()
#4 /home/u000/domains/website.co.uk/public_html/wp-admin/index.php(10): require_once('/home/u000...')
#5 {main}
  thrown`

**Comment by tblacker7** [comment] 2022-07-25 11:58
Thank you for this report - there is a pull review currently in flight to address this, which is caused by a dependency within the plugin: https://github.com/NHSLeadership/nightingale-companion/pull/44, we expect a release very soon.

**Comment by tblacker7** [comment] 2022-07-27 11:21
Fixed in #44 and in v1.3.2 release which is now available via your dashboard updates and/or wordpress.org repository (also wpackagist.com if that is your poison)

**Closed by tblacker7** 2022-07-27 11:21 UTC
